Optionally install uStreamer Debian package
mtlynch/ansible-role-ustreamer pull request #110
Opened 2023-05-18 14:54 UTC by jdeanwallace

Resolves https://github.com/tiny-pilot/ansible-role-ustreamer/issues/100

2023-05-22 12:49 UTC, jdeanwallace commented
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/110)

⏳ @jotaen4tinypilot please review this Pull Request

2023-05-22 20:20 UTC, jotaen4tinypilot requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/110)



<hr />

In: **Discussion**
I didn’t get around to reviewing this yet, but I installed the bundle from the scratch PR while testing https://github.com/tiny-pilot/ustreamer-debian/pull/6. I noticed that it still installs Janus via Ansible during the bundle installation:

```
TASK [ansible-role-ustreamer : enable Janus apt suite] ******************************************
changed: [localhost]

TASK [ansible-role-ustreamer : install Janus package and C header files] ************************
changed: [localhost]

TASK [ansible-role-ustreamer : patch Janus plugin.h file to successfully include refcount.h file] ***
changed: [localhost]
```

Wouldn’t that be obsolete when we install the uStreamer Debian package? (I might be missing something here, though?)


<hr />

👀 @jdeanwallace it's your turn please take a look

2023-05-23 13:06 UTC, jdeanwallace reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/110)



<hr />

In: **Discussion**
Oh no, the uStreamer Debian package just includes the uStreamer Janus plugin and not Janus itself (although Janus is indicated as a dependency). We still need to install Janus alongside uStreamer for WebRTC to work.


<hr />

👀 @jotaen4tinypilot it's your turn please take a look

2023-05-23 15:35 UTC, jotaen4tinypilot approved these changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/110)


<a href="https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/110"><img src="https://codeapprove.com/external/github-stamp-allbg.png" width="159" alt="Approved on CodeApprove" /></a>
✔️ Approved

👍

I’ve tested on device via the scratch PR.

<hr />

In: **Discussion**
Ah right, thanks – I forgot that Janus and the Janus *plugin* are two separate things!


<hr />

👀 @jdeanwallace it's your turn please take a look

2023-05-24 14:34 UTC, merged